MAIN_MAXPROPS 		= 50
MAIN_MAXINVENTORY 	= 40

--Graphical settings

MAIN_VIEWDISTANCE = 1000
MAIN_UISCALE_SPEEDOMETER = 0.8

MAIN_EXPENSIVE_CARLIGHT = true
MAIN_MOVIEMODE = false
MAIN_BOBBLEHEAD = false
